# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeedSX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Kingfisher'
 pod 'BSImagePicker'
 pod 'AWSCore'
 pod 'AWSCognito'
 pod 'AWSS3'
 pod "FirebaseCore"
 pod "FirebaseMessaging"
 pod 'youtube-ios-player-helper'
end
